"""Canonical error code constants for core behaviors."""

INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
ALREADY_IN_TARGET_STATE = "ALREADY_IN_TARGET_STATE"
JOB_NOT_ACTIVE = "JOB_NOT_ACTIVE"
DELETE_PENDING_CLEANUP = "DELETE_PENDING_CLEANUP"
CONTROL_CONFLICT = "CONTROL_CONFLICT"
